#!/usr/bin/env bash

valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all --trace-children=yes --suppressions=./readline.supp --track-fds=yes ./minishell

# valgrind --leak-check=full --show-leak-kinds=all --trace-children=yes --trace-children-skip=/usr/bin/\*,/bin/\*,~/bin/\* --suppressions=./readline.supp --track-fds=yes ./minishell